//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject2022
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QUANLYSIEUTHIEntities2 : DbContext
    {
        public QUANLYSIEUTHIEntities2()
            : base("name=QUANLYSIEUTHIEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHITIETHOADON> CHITIETHOADONs { get; set; }
        public virtual DbSet<HANGHOA> HANGHOAs { get; set; }
        public virtual DbSet<HOADON> HOADONs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<LOAIHANGHOA> LOAIHANGHOAs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<NHANVIENBANHANG> NHANVIENBANHANGs { get; set; }
        public virtual DbSet<NHANVIENKHO> NHANVIENKHOes { get; set; }
        public virtual DbSet<PHIEUHANGHOA> PHIEUHANGHOAs { get; set; }
        public virtual DbSet<PHIEUHANGXUAT> PHIEUHANGXUATs { get; set; }
        public virtual DbSet<PHIEUNHAP> PHIEUNHAPs { get; set; }
        public virtual DbSet<PHIEUXUAT> PHIEUXUATs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOANs { get; set; }
    
        public virtual ObjectResult<GETNV_Result> GETNV()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GETNV_Result>("GETNV");
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int SUANHANVIEN(string mANHANVIEN, string tENNHANVIEN, string dIACHI, Nullable<float> lUONGCOBAN, Nullable<int> dIEMTHUONG, Nullable<System.DateTime> nGAYSINH, string sDT, string gIOITINH, Nullable<float> tILETHUNHAPGIATANG, string mAQUANLY)
        {
            var mANHANVIENParameter = mANHANVIEN != null ?
                new ObjectParameter("MANHANVIEN", mANHANVIEN) :
                new ObjectParameter("MANHANVIEN", typeof(string));
    
            var tENNHANVIENParameter = tENNHANVIEN != null ?
                new ObjectParameter("TENNHANVIEN", tENNHANVIEN) :
                new ObjectParameter("TENNHANVIEN", typeof(string));
    
            var dIACHIParameter = dIACHI != null ?
                new ObjectParameter("DIACHI", dIACHI) :
                new ObjectParameter("DIACHI", typeof(string));
    
            var lUONGCOBANParameter = lUONGCOBAN.HasValue ?
                new ObjectParameter("LUONGCOBAN", lUONGCOBAN) :
                new ObjectParameter("LUONGCOBAN", typeof(float));
    
            var dIEMTHUONGParameter = dIEMTHUONG.HasValue ?
                new ObjectParameter("DIEMTHUONG", dIEMTHUONG) :
                new ObjectParameter("DIEMTHUONG", typeof(int));
    
            var nGAYSINHParameter = nGAYSINH.HasValue ?
                new ObjectParameter("NGAYSINH", nGAYSINH) :
                new ObjectParameter("NGAYSINH", typeof(System.DateTime));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var gIOITINHParameter = gIOITINH != null ?
                new ObjectParameter("GIOITINH", gIOITINH) :
                new ObjectParameter("GIOITINH", typeof(string));
    
            var tILETHUNHAPGIATANGParameter = tILETHUNHAPGIATANG.HasValue ?
                new ObjectParameter("TILETHUNHAPGIATANG", tILETHUNHAPGIATANG) :
                new ObjectParameter("TILETHUNHAPGIATANG", typeof(float));
    
            var mAQUANLYParameter = mAQUANLY != null ?
                new ObjectParameter("MAQUANLY", mAQUANLY) :
                new ObjectParameter("MAQUANLY", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SUANHANVIEN", mANHANVIENParameter, tENNHANVIENParameter, dIACHIParameter, lUONGCOBANParameter, dIEMTHUONGParameter, nGAYSINHParameter, sDTParameter, gIOITINHParameter, tILETHUNHAPGIATANGParameter, mAQUANLYParameter);
        }
    
        public virtual int SUAQUANLY(string mANHANVIEN, string tENNHANVIEN, string dIACHI, Nullable<float> lUONGCOBAN, Nullable<int> dIEMTHUONG, Nullable<System.DateTime> nGAYSINH, string sDT, string gIOITINH, Nullable<float> tILETHUNHAPGIATANG)
        {
            var mANHANVIENParameter = mANHANVIEN != null ?
                new ObjectParameter("MANHANVIEN", mANHANVIEN) :
                new ObjectParameter("MANHANVIEN", typeof(string));
    
            var tENNHANVIENParameter = tENNHANVIEN != null ?
                new ObjectParameter("TENNHANVIEN", tENNHANVIEN) :
                new ObjectParameter("TENNHANVIEN", typeof(string));
    
            var dIACHIParameter = dIACHI != null ?
                new ObjectParameter("DIACHI", dIACHI) :
                new ObjectParameter("DIACHI", typeof(string));
    
            var lUONGCOBANParameter = lUONGCOBAN.HasValue ?
                new ObjectParameter("LUONGCOBAN", lUONGCOBAN) :
                new ObjectParameter("LUONGCOBAN", typeof(float));
    
            var dIEMTHUONGParameter = dIEMTHUONG.HasValue ?
                new ObjectParameter("DIEMTHUONG", dIEMTHUONG) :
                new ObjectParameter("DIEMTHUONG", typeof(int));
    
            var nGAYSINHParameter = nGAYSINH.HasValue ?
                new ObjectParameter("NGAYSINH", nGAYSINH) :
                new ObjectParameter("NGAYSINH", typeof(System.DateTime));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var gIOITINHParameter = gIOITINH != null ?
                new ObjectParameter("GIOITINH", gIOITINH) :
                new ObjectParameter("GIOITINH", typeof(string));
    
            var tILETHUNHAPGIATANGParameter = tILETHUNHAPGIATANG.HasValue ?
                new ObjectParameter("TILETHUNHAPGIATANG", tILETHUNHAPGIATANG) :
                new ObjectParameter("TILETHUNHAPGIATANG", typeof(float));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SUAQUANLY", mANHANVIENParameter, tENNHANVIENParameter, dIACHIParameter, lUONGCOBANParameter, dIEMTHUONGParameter, nGAYSINHParameter, sDTParameter, gIOITINHParameter, tILETHUNHAPGIATANGParameter);
        }
    
        public virtual int THEMNHANVIEN(string mANHANVIEN, string tENNHANVIEN, string dIACHI, Nullable<float> lUONGCOBAN, Nullable<int> dIEMTHUONG, Nullable<System.DateTime> nGAYSINH, string sDT, string gIOITINH, Nullable<float> tILETHUNHAPGIATANG, string mAQUANLY)
        {
            var mANHANVIENParameter = mANHANVIEN != null ?
                new ObjectParameter("MANHANVIEN", mANHANVIEN) :
                new ObjectParameter("MANHANVIEN", typeof(string));
    
            var tENNHANVIENParameter = tENNHANVIEN != null ?
                new ObjectParameter("TENNHANVIEN", tENNHANVIEN) :
                new ObjectParameter("TENNHANVIEN", typeof(string));
    
            var dIACHIParameter = dIACHI != null ?
                new ObjectParameter("DIACHI", dIACHI) :
                new ObjectParameter("DIACHI", typeof(string));
    
            var lUONGCOBANParameter = lUONGCOBAN.HasValue ?
                new ObjectParameter("LUONGCOBAN", lUONGCOBAN) :
                new ObjectParameter("LUONGCOBAN", typeof(float));
    
            var dIEMTHUONGParameter = dIEMTHUONG.HasValue ?
                new ObjectParameter("DIEMTHUONG", dIEMTHUONG) :
                new ObjectParameter("DIEMTHUONG", typeof(int));
    
            var nGAYSINHParameter = nGAYSINH.HasValue ?
                new ObjectParameter("NGAYSINH", nGAYSINH) :
                new ObjectParameter("NGAYSINH", typeof(System.DateTime));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var gIOITINHParameter = gIOITINH != null ?
                new ObjectParameter("GIOITINH", gIOITINH) :
                new ObjectParameter("GIOITINH", typeof(string));
    
            var tILETHUNHAPGIATANGParameter = tILETHUNHAPGIATANG.HasValue ?
                new ObjectParameter("TILETHUNHAPGIATANG", tILETHUNHAPGIATANG) :
                new ObjectParameter("TILETHUNHAPGIATANG", typeof(float));
    
            var mAQUANLYParameter = mAQUANLY != null ?
                new ObjectParameter("MAQUANLY", mAQUANLY) :
                new ObjectParameter("MAQUANLY", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("THEMNHANVIEN", mANHANVIENParameter, tENNHANVIENParameter, dIACHIParameter, lUONGCOBANParameter, dIEMTHUONGParameter, nGAYSINHParameter, sDTParameter, gIOITINHParameter, tILETHUNHAPGIATANGParameter, mAQUANLYParameter);
        }
    
        public virtual int THEMQUANLY(string mANHANVIEN, string tENNHANVIEN, string dIACHI, Nullable<float> lUONGCOBAN, Nullable<int> dIEMTHUONG, Nullable<System.DateTime> nGAYSINH, string sDT, string gIOITINH, Nullable<float> tILETHUNHAPGIATANG)
        {
            var mANHANVIENParameter = mANHANVIEN != null ?
                new ObjectParameter("MANHANVIEN", mANHANVIEN) :
                new ObjectParameter("MANHANVIEN", typeof(string));
    
            var tENNHANVIENParameter = tENNHANVIEN != null ?
                new ObjectParameter("TENNHANVIEN", tENNHANVIEN) :
                new ObjectParameter("TENNHANVIEN", typeof(string));
    
            var dIACHIParameter = dIACHI != null ?
                new ObjectParameter("DIACHI", dIACHI) :
                new ObjectParameter("DIACHI", typeof(string));
    
            var lUONGCOBANParameter = lUONGCOBAN.HasValue ?
                new ObjectParameter("LUONGCOBAN", lUONGCOBAN) :
                new ObjectParameter("LUONGCOBAN", typeof(float));
    
            var dIEMTHUONGParameter = dIEMTHUONG.HasValue ?
                new ObjectParameter("DIEMTHUONG", dIEMTHUONG) :
                new ObjectParameter("DIEMTHUONG", typeof(int));
    
            var nGAYSINHParameter = nGAYSINH.HasValue ?
                new ObjectParameter("NGAYSINH", nGAYSINH) :
                new ObjectParameter("NGAYSINH", typeof(System.DateTime));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var gIOITINHParameter = gIOITINH != null ?
                new ObjectParameter("GIOITINH", gIOITINH) :
                new ObjectParameter("GIOITINH", typeof(string));
    
            var tILETHUNHAPGIATANGParameter = tILETHUNHAPGIATANG.HasValue ?
                new ObjectParameter("TILETHUNHAPGIATANG", tILETHUNHAPGIATANG) :
                new ObjectParameter("TILETHUNHAPGIATANG", typeof(float));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("THEMQUANLY", mANHANVIENParameter, tENNHANVIENParameter, dIACHIParameter, lUONGCOBANParameter, dIEMTHUONGParameter, nGAYSINHParameter, sDTParameter, gIOITINHParameter, tILETHUNHAPGIATANGParameter);
        }
    
        public virtual int XOANHANVIEN(string mANHANVIEN)
        {
            var mANHANVIENParameter = mANHANVIEN != null ?
                new ObjectParameter("MANHANVIEN", mANHANVIEN) :
                new ObjectParameter("MANHANVIEN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XOANHANVIEN", mANHANVIENParameter);
        }
    }
}
